//
//  joint.ts
//
//  Created by Nolan Huang on 15 Aug 2022.
//  Copyright 2022 Vircadia contributors.
//  Copyright 2022 DigiSomni LLC.
//
//  Distributed under the Apache License, Version 2.0.
//  See the accompanying file LICENSE or http://www.apache.org/licenses/LICENSE-2.0.html
//

// The jonits names to match the index of Vircadia
export const JointNames = [
    "Armature",
    "Hips",
    "EyeLeft",
    "EyeRight",
    "Wolf3D_Body",
    "Wolf3D_Hair",
    "Wolf3D_Head",
    "Wolf3D_Outfit_Bottom",
    "Wolf3D_Outfit_Footwear",
    "Wolf3D_Outfit_Top",
    "Wolf3D_Teeth",
    "Spine",
    "LeftUpLeg",
    "RightUpLeg",
    "Spine1",
    "LeftLeg",
    "RightLeg",
    "Spine2",
    "LeftFoot",
    "RightFoot",
    "Neck",
    "LeftShoulder",
    "RightShoulder",
    "LeftToeBase",
    "RightToeBase",
    "Head",
    "HeadTop_End",
    "LeftArm",
    "RightArm",
    "LeftToe_End",
    "RightToe_End",
    "LeftEye",
    "RightEye",
    "LeftForeArm",
    "RightForeArm",
    "LeftHand",
    "LeftHandRing1",
    "LeftHandThumb1",
    "RightHand",
    "LeftHandIndex1",
    "LeftHandPinky1",
    "LeftHandRing2",
    "LeftHandMiddle1",
    "RightHandThumb1",
    "RightHandIndex1",
    "LeftHandThumb2",
    "RightHandPinky1",
    "LeftHandIndex2",
    "LeftHandPinky2",
    "LeftHandRing3",
    "LeftHandMiddle2",
    "RightHandMiddle1",
    "RightHandThumb2",
    "RightHandIndex2",
    "RightHandRing1",
    "LeftHandThumb3",
    "LeftHandIndex3",
    "RightHandIndex3",
    "RightHandMiddle2",
    "RightHandThumb3",
    "LeftHandPinky3",
    "RightHandRing2",
    "LeftHandRing4",
    "LeftHandMiddle3",
    "LeftHandThumb4",
    "RightHandPinky2",
    "LeftHandIndex4",
    "RightHandThumb4",
    "RightHandIndex4",
    "RightHandRing3",
    "LeftHandMiddle4",
    "RightHandMiddle3",
    "RightHandPinky3",
    "LeftHandPinky4",
    "RightHandRing4",
    "RightHandPinky4",
    "RightHandMiddle4"
];
