name: '🖥️ Desktop Build'
on:
  pull_request:
    branches: [ "master" ]

jobs:
  desktop-build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies (Ubuntu Only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install Dependencies
        run: npm ci

      - name: Build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VRCA_DESKTOP_MODE: build
        run: cd desktop && npm run tauri build

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: build-desktop-${{ matrix.platform }}-${{ github.event.number }}
          path: |
            ${{ runner.workspace }}/vircadia-web/desktop/src-tauri/target/release/bundle/**/*.app
            ${{ runner.workspace }}/vircadia-web/desktop/src-tauri/target/release/bundle/**/*.dmg
            ${{ runner.workspace }}/vircadia-web/desktop/src-tauri/target/release/bundle/**/*.deb
            ${{ runner.workspace }}/vircadia-web/desktop/src-tauri/target/release/bundle/**/*.AppImage
            ${{ runner.workspace }}/vircadia-web/desktop/src-tauri/target/release/bundle/**/*.msi
            ${{ runner.workspace }}/vircadia-web/desktop/src-tauri/target/release/bundle/**/*.exe
          if-no-files-found: error
