# Automatically deploy the latest changes to the FTP server.
on:
  # Triggers the workflow on push events to the specified branch.
  push:
    branches: [ "demo/Learnaverse" ]

  # Allows this workflow to be run manually from the Actions tab.
  workflow_dispatch:

name: 🚀 Auto-Deploy (Learnaverse)
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - uses: actions/setup-node@master
      with:
        node-version: 16.x

    - name: 📥 Install project dependencies
      run: npm install

    - name: ⚒️ Build the project
      run: npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.vircadia.com
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: dist/spa/
        server-dir: ${{ secrets.learnaverse_ftp_dir }}/
        dry-run: false
